// Code for insertation sort for array

#include <stdio.h> //standard input output library
#include <stdlib.h> //standard library for malloc
#include <time.h> //time library for time(NULL)

//**********************************************************************

int Make_array(int n){   //generate array of n elements
    int *sample_array = malloc (n*sizeof(int)); //allocate memory for n elements

    if(sample_array) { //if memory allocation is successful
        for (int counter = 0; counter < n; counter++){ sample_array[counter] = rand()%1000;} //generate a randok number between 0-999
        
    }
    return sample_array; //return the address of the array
}

//**********************************************************************

//Output array of n elements and was generated by Array_generate

void printArray(int *a, int n){         // Printing the array of n elements
    printf("Array = ");                 //printing the array
    for (int counter = 0; counter < n; counter++){  //for loop to print the array
        printf(counter?", %d":"%d", a[counter]); // outputing the particular element of the array at position i
    }
    printf("\n"); //new line
}

//**********************************************************************

//Insertation sort for array

//**********************************************************************

void insertationSort(int *a, int n){    //insertation sort for array
    int counter, j, key;                //initializing the counter, j and key

    for (counter = 1; counter < n; counter++){ //for loop to sort the array
        key = a[counter];               //key is the element at position counter
        j = counter-1;                  //j is the position of the element before the element at position counter

        while (j >= 0 && a[j] > key){   //while loop to sort the array
            a[j+1] = a[j];              //shifting the elements to the right
            j--;                        //decrementing j
        }
        a[j+1] = key;                    //inserting the key at the correct position
    }
}

//**********************************************************************

//Runing the code to check the output and insertation sort for array

//**********************************************************************
int main(int argc, char **argv){ 
    int *a;          //initializing the array
    int n = 8;       //initializing the number of elements in the array

    srand(time(NULL));  //generating random numbers

    a = Make_array(n); //calling the function to generate the array
    printArray(a,n);   //calling the function to print the array

    insertationSort(a,n); //calling the function to sort the array
    printArray(a,n);     //calling the function to print the array
    
    free(a);          //freeing the memory
    return 0;         //returning 0
}


//**********************************************************************

//End of the code

//**********************************************************************