//Selection Sort for Array

#include <stdio.h> //standard input output library
#include <stdlib.h> //standard library for malloc, free, rand, srand
#include <time.h> //time library for time(NULL)


//**********************************************


int Array_generate(int n){                   //generate array of n elements
    int *array_sample = malloc (n*sizeof(int));         //allocate memory for n elements
    if(array_sample) {                                  //if memory allocation is successful
        for (int i = 0; i < n; i++){ array_sample[i] = rand()%1000;} //find a randon number between 0 and 999 and store it in the array
    }
    return array_sample; //return the address of the array
}


//**********************************************

//output array of n elements and was generated by Array_generate

void output_array(int *a, int n){  // Printing the array of n elements
    for (int i = 0; i < n; i++){   //for loop to print the array
        printf(i?", %d":"%d", a[i]); // outputing the particular element of the array at position i
    }
    printf("\n");                    //new line
}

//**********************************************

int finding_max_value(int *a, int n){ //finding the position of the max element in the array
    if (n<1) {return -1;} //if the array is empty, return -1, Checking for corner cases

    int imax = 0;   //initializing the position of the max element to 0

    for (int i = 1; i < n; i++){ //for loop to find the position of the max element
        if (a[i] > a[imax]) imax = i; //if the element at position i is greater than the element at position imax, then update the position of the max element to i
    }
    return imax; //return the position of the max element
}

//**********************************************

void swap (int *a, int *b){  //swapping the elements at position a and b
   
    int array_sample = *a; *a = *b; *b = array_sample;    //swapping the elements at position a and b
}
//**********************************************

// Selection Sort for Array

//**********************************************

void selectionSort(int *a, int n){ //selection sort for array
    int imax, array_sample;        //initializing the position of the max element and the array_sample

    for (int i = n; i > 0; i--){   //for loop to sort the array
        imax = finding_max_value(a, i); //finding the position of the max element in the array
        swap(&a[imax], &a[i-1]);  //swapping the elements at position imax and i-1
    }
}
//**********************************************

// Running the program to check the output and its selection sort
//**********************************************
main(int argc, char **argv){ 
    int *a;               //initializing the array
    int n = 8;            //initializing the number of elements in the array
    NodeAddress list;      //initializing the list
    srand(time(NULL));     //initializing the random number generator

    a = Array_generate(n);      //generating the array of n elements

    output_array(a,n);         //outputing the array of n elements
    selectionSort(a,n);        //sorting the array of n elements
    output_array(a,n);        //outputing the array of n elements after sorting

    free(a);                 //freeing the memory allocated to the array
    
    return 0;                //returning 0
}


//**********************************************

// END OF PROGRAM

//**********************************************